### ISSUE TITLE
DPF/DGL is missing for this build

### ISSUE THREAD

**Issue by mikobuntu** [rghvdberg/a2m#1]
Hi I tried to built a2m and pulling in the submodules I notice they are empty. I proceed to copy the dpf files from ninjas2 into the build tree, but now i get this error below :-  

 -I../../aubio/src -I../../dpf/distrho -I../../dpf/dgl -MD -MP -c -o a2mPlugin.cpp.o
In file included from ../../dpf/distrho/extra/../DistrhoUtils.hpp:20:0,
                 from ../../dpf/distrho/extra/String.hpp:20,
                 from ../../dpf/distrho/DistrhoPlugin.hpp:20,
                 from a2mPlugin.cpp:17:
../../dpf/distrho/extra/../src/DistrhoDefines.h:136:31: error: expected declaration before ‘}’ token
 #define END_NAMESPACE_DISTRHO }
                               ^
a2mPlugin.hpp:71:1: note: in expansion of macro ‘END_NAMESPACE_DISTRHO’
 END_NAMESPACE_DISTRHO
 ^~~~~~~~~~~~~~~~~~~~~
../Makefile.mk:80: recipe for target 'a2mPlugin.cpp.o' failed
make[1]: *** [a2mPlugin.cpp.o] Error 1
make[1]: Leaving directory '/home/superlinuxaudioguru/a2m/plugins/a2m'
Makefile:20: recipe for target 'plugins' failed

**Comment by rghvdberg** [comment]
oh, this project is basically on hold/dead 
I'm sorry I've wasted your time.
Gonna close this repo
